"""Incident test (rung 4), named for crew#323: the auto-ticket hook took a compaction
summary as the founder's first words and opened an issue titled "This session is being
continued from a previous conversation...". founder_words must skip harness text and return
the first line the founder actually typed, or "" when there is none."""
from __future__ import annotations

import importlib.util
import json
import os
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))


def _load():
    spec = importlib.util.spec_from_file_location("ticket_gate", os.path.join(HERE, "ticket-gate.py"))
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _transcript(*texts: str) -> str:
    fd, path = tempfile.mkstemp(suffix=".jsonl")
    with os.fdopen(fd, "w") as fh:
        for t in texts:
            fh.write(json.dumps({"message": {"role": "user", "content": t}}) + "\n")
    return path


class TicketGateSkipsCompactionSummary(unittest.TestCase):
    def test_summary_then_founder_prompt_returns_the_prompt(self) -> None:
        tg = _load()
        path = _transcript(
            "This session is being continued from a previous conversation that ran out of context. Summary: ...",
            "fix the llm row",
        )
        self.assertEqual(tg.founder_words(path), "fix the llm row")

    def test_summary_alone_returns_empty(self) -> None:
        tg = _load()
        path = _transcript(
            "This session is being continued from a previous conversation that ran out of context.",
            "Caveat: The messages below were generated by the user while running local commands.",
            "Stop hook feedback: ...",
        )
        self.assertEqual(tg.founder_words(path), "")

    def test_liveness_probe_is_not_founder_words(self) -> None:
        """crew#334-#337: a monitor's probe ("Reply with the single word ALIVE") was filed four times
        as the founder's request. Same rule as the summary: harness text is skipped, his line after
        it is returned."""
        tg = _load()
        probe = "Answer with one word and nothing else. Reply with the single word ALIVE."
        self.assertEqual(tg.founder_words(_transcript(probe)), "")
        self.assertEqual(tg.founder_words(_transcript(probe, "what are you doing")), "what are you doing")

    def test_genuine_first_line_still_returned(self) -> None:
        tg = _load()
        self.assertEqual(tg.founder_words(_transcript("i need an architectual review")), "i need an architectual review")


if __name__ == "__main__":
    unittest.main()
