#!/usr/bin/env python3
"""Is this file kept anywhere? One answer, one place (LAW 24).

This module exists because the question was answered three times in one session
and got a different wrong answer twice:

  * asking whether the file's own DIRECTORY is a git repo says "no" for every
    file the estate mirrors in from outside a checkout, which is most of them;
  * joining a mirror path with os.path.relpath() produces "laws/AGENTS.md/."
    for a single-file mirror, which never exists, so the laws themselves read
    as untracked.

Anything that needs to know whether a path is kept imports covered() from here.
Nobody re-derives it.
"""
import json, os, subprocess

HOME = os.path.expanduser("~")
REPO = os.path.join(HOME, ".claude", "scripts")
MANIFEST = os.path.join(REPO, "tracked.json")


def mirrors():
    """The live -> repo pairs tracked.json keeps in step."""
    out = []
    for e in json.load(open(MANIFEST)):
        out.append((os.path.expanduser(e["live"]).rstrip("/"),
                    os.path.join(REPO, e["repo"])))
    return out


def _git_tracked(path):
    d = path if os.path.isdir(path) else os.path.dirname(path)
    r = subprocess.run(["git", "-C", d, "rev-parse", "--show-toplevel"],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None
    top = r.stdout.strip()
    if subprocess.run(["git", "-C", top, "ls-files", "--error-unmatch", path],
                      capture_output=True).returncode == 0:
        return "tracked in " + top.replace(HOME, "~")
    return None


def _mirrored(path, mirror_map):
    for live, repo_dir in mirror_map:
        if path == live:
            # A single-file mirror: the repo path IS the file, not a directory
            # to join a relative path onto.
            return ("mirrored to " + os.path.relpath(repo_dir, REPO)
                    if os.path.exists(repo_dir) else None)
        if path.startswith(live + os.sep):
            m = os.path.join(repo_dir, os.path.relpath(path, live))
            if os.path.exists(m):
                return "mirrored to " + os.path.relpath(m, REPO)
    return None


def covered(path, mirror_map=None, generated=None):
    """Why this path is kept, or None when nothing keeps it.

    Three legal answers, in the order they are cheapest to check:
      tracked in its own repo / mirrored in by tracked.json / generated output
      whose generator is itself tracked (the LAW 24 exclusion).
    """
    if mirror_map is None:
        mirror_map = mirrors()
    real = os.path.realpath(path)
    for p in (path, real) if real != path else (path,):
        why = _git_tracked(p)
        if why:
            return why
        why = _mirrored(p, mirror_map)
        if why:
            return why
    if generated and path in generated:
        gen = os.path.join(REPO, generated[path])
        if os.path.exists(gen):
            return "generated by " + generated[path]
    return None
