#!/usr/bin/env python3
"""Every program a launchd job runs is in git, or it is a hole (LAW 24).

A plist committed to launchagents/ proves the job definition is kept. It says
nothing about the script the job actually executes, and that script is the part
that would ruin a week if it vanished.

Three things are legal and are not holes:
  * the file is tracked in whatever repo contains it
  * the file lives outside any repo but is mirrored into one by tracked.json
  * the file is generated output whose generator is tracked (LAW 24 exclusion)

Exit 0 when there are no holes, 1 when there are.
"""
import glob, json, os, plistlib, subprocess, sys

HOME = os.path.expanduser("~")
REPO = os.path.join(HOME, ".claude", "scripts")
TRACKED = os.path.join(REPO, "tracked.json")

# Jobs the estate did not install. Valve, Apple and friends are not ours to fix.
FOREIGN = ("com.apple", "com.valvesoftware", "com.adobe", "com.docker",
           "com.cisco", "com.ollama", "com.openssh", "com.google", "com.microsoft")

# Interpreters and system binaries. The interpreter is not the runner; the
# script it is handed is, and that script is checked on its own.
def is_system(path):
    return (path.startswith(("/usr/", "/bin/", "/sbin/", "/System/", "/opt/homebrew/"))
            or os.path.basename(path) in
            ("python3", "python", "node", "bash", "sh", "zsh", "env", "caffeinate"))

# A build product is excluded only while the thing that builds it is tracked.
GENERATED = {
    os.path.join(HOME, ".claude/bin/estate-runner"):
        "estate/make-runner.sh",
}

def mirrors():
    out = []
    for e in json.load(open(TRACKED)):
        out.append((os.path.expanduser(e["live"]).rstrip("/"),
                    os.path.join(REPO, e["repo"])))
    return out

def covered(path, mirror_map):
    d = os.path.dirname(path)
    top = subprocess.run(["git", "-C", d, "rev-parse", "--show-toplevel"],
                         capture_output=True, text=True)
    if top.returncode == 0:
        t = top.stdout.strip()
        if subprocess.run(["git", "-C", t, "ls-files", "--error-unmatch", path],
                          capture_output=True).returncode == 0:
            return "tracked in " + os.path.relpath(t, HOME)
    for live, repo_dir in mirror_map:
        if path == live or path.startswith(live + "/"):
            m = os.path.join(repo_dir, os.path.relpath(path, live))
            if os.path.exists(m):
                return "mirrored to " + os.path.relpath(m, REPO)
    if path in GENERATED:
        gen = os.path.join(REPO, GENERATED[path])
        if os.path.exists(gen):
            return "generated by " + GENERATED[path]
    return None

def runners(argv):
    """The program arguments that name a file on disk, minus interpreters and
    minus anything introduced by a flag, which is an output path, not a runner."""
    out, skip = [], False
    for i, a in enumerate(argv):
        if skip:
            skip = False
            continue
        if a.startswith("-"):
            # a flag takes its value with it: --out FILE, --error-log FILE
            if "=" not in a and i + 1 < len(argv) and not argv[i + 1].startswith("-"):
                skip = True
            continue
        if a.startswith("/") and not is_system(a):
            out.append(a)
    return out

def main():
    mirror_map = mirrors()
    holes, ok, jobs = [], [], 0
    for f in sorted(glob.glob(os.path.join(HOME, "Library/LaunchAgents/*.plist"))):
        label = os.path.basename(f)[:-6]
        if label.startswith(FOREIGN):
            continue
        jobs += 1
        try:
            argv = plistlib.load(open(f, "rb")).get("ProgramArguments", [])
        except Exception as e:
            holes.append((label, "unreadable plist: %s" % e))
            continue
        for a in runners(argv):
            if not os.path.exists(a):
                holes.append((label, "target missing: %s" % a))
                continue
            why = covered(a, mirror_map)
            if why is None:
                holes.append((label, "not in git: %s" % a))
            else:
                ok.append((label, os.path.relpath(a, HOME), why))

    if "--quiet" not in sys.argv:
        for label, path, why in ok:
            print("  ok    %-34s %s  (%s)" % (label, path, why))
    print("jobs: %d  runners in git: %d  holes: %d" % (jobs, len(ok), len(holes)))
    for label, why in holes:
        print("  HOLE  %s: %s" % (label, why))
    return 1 if holes else 0

if __name__ == "__main__":
    sys.exit(main())
